'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const core = require('../src/core');
const rules = require('../src/rules');
const demo = require('../src/demo-data');
/** Parse and aggregate a CSV using small chunks to exercise streaming boundaries. */
function analyze(csv, chunk = 17) {
  const aggregator = core.createAggregator({
    rules
  });
  const parser = core.createCsvParser({
    onRow: aggregator.add
  });
  for (let index = 0; index < csv.length; index += chunk) {
    parser.push(csv.slice(index, index + chunk));
  }
  parser.end();
  return aggregator.result();
}
const header = 'File Name,Size,Allocated\r\n';
const row = (path, bytes, allocated = bytes) =>
  '"' + path.replaceAll('"', '""') + '",' + bytes + ',' + allocated + '\r\n';
test('说明行、中文表头、额外列、跨块引号和断行', () => {
  const rows = [];
  const parser = core.createCsvParser({
    onRow: (row) => rows.push(row)
  });
  const text =
    '\ufeffGenerated by WizTree\r\n说明\r\n已分配,文件名称,大小,其他\r\n4096,"C:\\中文\\带""引号,文件\n名.dat",8192,忽略\r\n';
  for (const character of text) {
    parser.push(character);
  }
  parser.end();
  assert.deepEqual(rows, [
    {
      path: 'C:\\中文\\带"引号,文件\n名.dat',
      size: 8192,
      allocated: 4096,
      isDir: false
    }
  ]);
});
test('编码识别和中文路径', () => {
  for (const [bytes, encoding] of [
    [Buffer.from('C:\\中文\\'), 'utf-8'],
    [Buffer.from([0x43, 0x3a, 0x5c, 0xd6, 0xd0, 0xce, 0xc4, 0x5c]), 'gb18030'],
    [
      Buffer.concat([
        Buffer.from([255, 254]),
        Buffer.from('C:\\中文\\', 'utf16le')
      ]),
      'utf-16le'
    ]
  ]) {
    assert.equal(core.decodeHelpers.sniffEncoding(bytes), encoding);
    assert.equal(new TextDecoder(encoding).decode(bytes), 'C:\\中文\\');
  }
  assert.equal(
    core.decodeHelpers.sniffEncoding(Buffer.from([0x61, 0xe4, 0xb8])),
    'utf-8'
  );
  const bytes = Buffer.from([0xd6, 0xd0, 0xce, 0xc4]);
  const decodedPath = 'C:\\' + new TextDecoder('gb18030').decode(bytes) + '\\';
  assert.equal(analyze(header + row(decodedPath, 9)).folderRows, 1);
});
test('硬链接不计入占用、空分配使用大小、非法行统计', () => {
  const result = analyze(
    header +
      row('C:\\a', 10, '04096') +
      row('C:\\b', 20, '') +
      row('C:\\c', 30, '无效')
  );
  assert.equal(result.totalBytes, 20);
  assert.equal(result.skipped, 1);
  assert.equal(result.fileRows, 2);
});
test('文件列表与文件夹列表建议一致、混合列表不重复', () => {
  const folder = 'C:\\Users\\小明\\Downloads\\';
  const files = row(folder + '甲', 40) + row(folder + '乙', 60);
  for (const csv of [files, row(folder, 100), row(folder, 100) + files]) {
    const result = analyze(header + csv);
    assert.equal(result.suggestions[0].bytes, 100);
    assert.equal(result.maxBytes, 100);
  }
});
test('文档与微信嵌套去重，目录边界和大小写正确', () => {
  const result = analyze(
    header +
      row('C:\\Users\\小明\\Documents\\', 100) +
      row('C:\\Users\\小明\\Documents\\WeChat Files\\', 70)
  );
  assert.equal(
    result.suggestions.find((suggestion) => suggestion.id === 'wechat').bytes,
    70
  );
  assert.equal(
    result.suggestions.find((suggestion) => suggestion.id === 'documents')
      .bytes,
    100
  );
  assert.equal(result.maxBytes, 100);
  assert.equal(
    core.unionBytes([
      {
        path: 'C:\\A',
        bytes: 100
      },
      {
        path: 'c:\\a-b',
        bytes: 20
      },
      {
        path: 'c:\\a\\child',
        bytes: 50
      },
      {
        path: 'c:\\a',
        bytes: 90
      }
    ]),
    120
  );
});
test('空档位、空 CSV 与错误 CSV', () => {
  const result = analyze(header + row('C:\\Windows\\', 100));
  assert.deepEqual(result.suggestions, []);
  assert.equal(result.maxBytes, 0);
  assert.equal(analyze(header).rowCount, 0);
  assert.throws(() => analyze('不是表格'), /表头/);
  assert.throws(() => analyze(header + '"未闭合'), /引号/);
});
test('互斥分类桶、根目录剩余与混合列表', () => {
  const csv =
    header +
    row('C:\\', 1000) +
    row('C:\\Windows\\', 200) +
    row('C:\\Windows\\Temp\\', 80) +
    row('C:\\Windows\\Temp\\a', 80) +
    row('C:\\Program Files\\', 100) +
    row('C:\\ProgramData\\', 50) +
    row('C:\\Users\\甲\\AppData\\', 100) +
    row('C:\\Users\\甲\\Downloads\\', 100) +
    row('C:\\Users\\甲\\Documents\\', 150) +
    row('C:\\Users\\甲\\Documents\\WeChat Files\\', 100) +
    row('C:\\Users\\甲\\OneDrive 公司\\', 50) +
    row('C:\\$Recycle.Bin\\', 50);
  const result = analyze(csv);
  const categoryTotals = Object.fromEntries(
    result.categories.map((category) => [category.id, category.bytes])
  );
  assert.deepEqual(categoryTotals, {
    system: 200,
    programs: 100,
    appdata: 150,
    personal: 200,
    downloads: 100,
    recycle: 50,
    other: 200
  });
  assert.equal(result.totalBytes, 1000);
  assert.equal(result.kind, 'mixed');
  const fileResult = analyze(
    header + row('C:\\pagefile.sys', 30) + row('C:\\Users\\甲\\AppData\\a', 20)
  );
  assert.equal(fileResult.totalBytes, 50);
  assert.equal(
    fileResult.categories.find((category) => category.id === 'other').bytes,
    30
  );
});
test('全部锚点可重算并集，明细只保留前 50 条', () => {
  let csv = header;
  for (let index = 0; index < 80; index++) {
    csv += row('D:\\项目' + index + '\\node_modules\\', index + 1);
  }
  const result = analyze(csv);
  const suggestion = result.suggestions[0];
  assert.equal(suggestion.anchorCount, 80);
  assert.equal(suggestion.anchors.length, 50);
  assert.equal(suggestion.allAnchors.length, 80);
  assert.equal(result.maxBytes, 3240);
  assert.equal(core.unionBytes(suggestion.allAnchors), suggestion.bytes);
});
test('任意深度取第一次锚点、盘符通配、规则优先级', () => {
  const result = analyze(
    header +
      row('D:\\项目\\node_modules\\', 100) +
      row('D:\\项目\\node_modules\\包\\node_modules\\', 80) +
      row('D:\\Users\\甲\\Documents\\WeChat Files\\a', 30)
  );
  assert.equal(
    result.suggestions.find((suggestion) => suggestion.id === 'dependencies')
      .bytes,
    100
  );
  assert.equal(
    result.suggestions.find((suggestion) => suggestion.id === 'wechat').bytes,
    30
  );
  assert.ok(
    !result.suggestions.find((suggestion) => suggestion.id === 'documents')
  );
});
test('示例包含三档，中文容量格式', () => {
  const result = analyze(demo);
  for (const tier of ['light', 'medium', 'heavy']) {
    assert.ok(
      result.suggestions.some((suggestion) => suggestion.tier === tier)
    );
  }
  assert.equal(core.formatBytes(12.3 * 1073741824), '约 12.3 GB');
  assert.equal(core.formatBytes(850 * 1048576), '850 MB');
});
module.exports = {
  analyze
};
test('纯文件列表父目录包含被优先规则认领的子目录，不受行顺序影响', () => {
  const documents = 'C:\\Users\\甲\\Documents\\';
  const wechat = documents + 'WeChat Files\\';
  for (const files of [
    row(documents + '笔记.txt', 30) + row(wechat + '聊天.dat', 70),
    row(wechat + '聊天.dat', 70) + row(documents + '笔记.txt', 30)
  ]) {
    const result = analyze(header + files);
    assert.equal(
      result.suggestions.find((suggestion) => suggestion.id === 'documents')
        .bytes,
      100
    );
    assert.equal(
      result.suggestions.find((suggestion) => suggestion.id === 'wechat').bytes,
      70
    );
    assert.equal(result.maxBytes, 100);
    const folders = analyze(header + row(documents, 100) + row(wechat, 70));
    assert.deepEqual(result.suggestions, folders.suggestions);
  }
});

test('建议仅保留最大的 300 个锚点，并集使用截断后的列表', () => {
  let csv = header;
  for (let index = 0; index < 350; index++) {
    csv += row(`D:\\项目${index}\\node_modules\\`, index + 1);
  }
  const result = analyze(csv);
  const suggestion = result.suggestions[0];
  assert.equal(suggestion.anchorCount, 350);
  assert.equal(suggestion.allAnchors.length, 300);
  assert.equal(suggestion.anchors.length, 50);
  assert.equal(suggestion.allAnchors[0].bytes, 350);
  assert.equal(suggestion.allAnchors[299].bytes, 51);
  assert.equal(suggestion.bytes, ((350 + 51) * 300) / 2);
  assert.equal(result.maxBytes, suggestion.bytes);
  assert.equal(core.unionBytes(suggestion.allAnchors), suggestion.bytes);
});
