'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { spawnSync } = require('node:child_process');
const core = require('../src/core');
const rules = require('../src/rules');
const defaultPath = '/workspace/tools/pwsh/pwsh';
const pwsh =
  process.env.PWSH || (fs.existsSync(defaultPath) ? defaultPath : 'pwsh');
const available =
  spawnSync(
    pwsh,
    ['-NoProfile', '-Command', '$PSVersionTable.PSVersion.ToString()'],
    {
      encoding: 'utf8'
    }
  ).status === 0;
const quote = (text) => "'" + text.replaceAll("'", "''") + "'";
test(
  'PowerShell 纯函数：筛选、重排列、中文引号、嵌入防闭合，与核心结果一致',
  {
    skip: !available
  },
  () => {
    const directory = fs.mkdtempSync(
      path.join(os.tmpdir(), '磁盘报告 (测试) ')
    );
    const input = path.join(directory, '输入.csv');
    const compact = path.join(directory, '紧凑.csv');
    const output = path.join(directory, '报告.html');
    const template = path.join(directory, '模板.html');
    const csv =
      'Generated by WizTree\r\n额外,Allocated,File Name,Size\r\n无,1,"C:\\",1\r\n无,20971520,"C:\\Users\\小明\\Downloads\\",20971520\r\n无,10485760,"C:\\Windows\\Temp\\",10485760\r\n无,30,"C:\\小目录\\",30\r\n无,20971520,"C:\\文件.txt",20971520\r\n无,10485760,"C:\\带""引号\\",10485760\r\n';
    fs.writeFileSync(input, '\ufeff' + csv);
    fs.writeFileSync(
      template,
      fs.readFileSync(path.join(__dirname, '../src/report.html'))
    );
    const command =
      '. ' +
      quote(path.join(__dirname, '../src/diskpilot-lite.ps1')) +
      ' -NoRun; $csv = Convert-WizTreeCsvToEmbed -CsvPath ' +
      quote(input) +
      '; [IO.File]::WriteAllText(' +
      quote(compact) +
      ',$csv); New-ReportHtml -TemplatePath ' +
      quote(template) +
      ' -OutPath ' +
      quote(output) +
      ' -CsvText ($csv + "</script>危险") -Meta @{source="real";drive="C:";adminScan=$true};';
    const run = spawnSync(pwsh, ['-NoProfile', '-Command', command], {
      encoding: 'utf8'
    });
    assert.equal(run.status, 0, run.stdout + run.stderr);
    const text = fs.readFileSync(compact, 'utf8');
    const rows = [];
    const parser = core.createCsvParser({
      onRow: (row) => rows.push(row)
    });
    parser.push(text);
    parser.end();
    assert.equal(rows.length, 4);
    assert.equal(rows[0].path, 'C:\\');
    assert.ok(rows.some((row) => row.path === 'C:\\带"引号\\'));
    function aggregate(text, filterFolders) {
      const aggregator = core.createAggregator({
        rules
      });
      const filteredParser = core.createCsvParser({
        onRow: (row) => {
          if (
            !filterFolders ||
            (row.isDir && (row.allocated >= 10485760 || row.path === 'C:\\'))
          ) {
            aggregator.add(row);
          }
        }
      });
      filteredParser.push(text);
      filteredParser.end();
      return aggregator.result();
    }
    assert.deepEqual(aggregate(text), aggregate(csv, true));
    const html = fs.readFileSync(output, 'utf8');
    assert.match(html, /<\\\/script>危险/);
    assert.match(html, /"source":"real"/);
    assert.match(html, /"adminScan":true/);
    assert.notEqual(html.charCodeAt(0), 0xfeff);
  }
);
test(
  'PowerShell UTF-16 BOM、空分配回退与无表头默认列',
  {
    skip: !available
  },
  () => {
    const directory = fs.mkdtempSync(path.join(os.tmpdir(), '磁盘编码 '));
    const input = path.join(directory, '输入.csv');
    const output = path.join(directory, '输出.csv');
    fs.writeFileSync(
      input,
      Buffer.concat([
        Buffer.from([255, 254]),
        Buffer.from(
          'File Name,Size,Allocated\r\n"C:\\Users\\中文\\Downloads\\",50,\r\n',
          'utf16le'
        )
      ])
    );
    const command =
      '. ' +
      quote(path.join(__dirname, '../src/diskpilot-lite.ps1')) +
      ' -NoRun; $text=Convert-WizTreeCsvToEmbed -CsvPath ' +
      quote(input) +
      ' -MinBytes 0; [IO.File]::WriteAllText(' +
      quote(output) +
      ',$text);';
    const run = spawnSync(pwsh, ['-NoProfile', '-Command', command], {
      encoding: 'utf8'
    });
    assert.equal(run.status, 0, run.stderr);
    assert.match(fs.readFileSync(output, 'utf8'), /中文\\Downloads\\",50,50/);
    fs.writeFileSync(input, '"C:\\",100,100\r\n');
    const again = spawnSync(pwsh, ['-NoProfile', '-Command', command], {
      encoding: 'utf8'
    });
    assert.equal(again.status, 0, again.stderr);
    assert.match(fs.readFileSync(output, 'utf8'), /"C:\\",100,100/);
  }
);

test(
  'PowerShell 首列快速路径：中文逗号、额外列、文件跳过与最小目录大小',
  { skip: !available },
  (context) => {
    const directory = fs.mkdtempSync(path.join(os.tmpdir(), '磁盘快速解析 '));
    context.after(() => fs.rmSync(directory, { recursive: true, force: true }));
    const input = path.join(directory, '输入.csv');
    const output = path.join(directory, '输出.csv');
    const csv = [
      'Generated by WizTree',
      'File Name,Extra,Allocated,Size,More',
      '"C:\\",无,1,1,无',
      '"C:\\中文,带""引号\\",无,20971520,20971521,无',
      'C:\\未加引号\\,无,10485760,10485761,无',
      '"C:\\小目录\\",无,30,30,无',
      '"C:\\文件.txt",无,20971520,20971520,无',
      '"C:\\无效数字文件.txt",无,不是数字,不是数字,无',
      ''
    ].join('\r\n');
    fs.writeFileSync(input, '\ufeff' + csv);
    const command = [
      `. ${quote(path.join(__dirname, '../src/diskpilot-lite.ps1'))} -NoRun`,
      // The header is the only line allowed through the slow parser in this fixture.
      '$originalSplit = ${function:Split-CsvLine}',
      '$script:splitCalls = 0',
      'function Split-CsvLine { param([string]$Line); $script:splitCalls++; if ($script:splitCalls -gt 1) { throw "Slow data path" }; & $originalSplit $Line }',
      `$text = Convert-WizTreeCsvToEmbed -CsvPath ${quote(input)}`,
      `[IO.File]::WriteAllText(${quote(output)}, $text)`
    ].join('; ');
    const run = spawnSync(pwsh, ['-NoProfile', '-Command', command], {
      encoding: 'utf8'
    });
    assert.equal(run.status, 0, run.stdout + run.stderr);
    const rows = [];
    const parser = core.createCsvParser({ onRow: (row) => rows.push(row) });
    parser.push(fs.readFileSync(output, 'utf8'));
    parser.end();
    assert.deepEqual(rows, [
      { path: 'C:\\', size: 1, allocated: 1, isDir: true },
      {
        path: 'C:\\中文,带"引号\\',
        size: 20971521,
        allocated: 20971520,
        isDir: true
      },
      {
        path: 'C:\\未加引号\\',
        size: 10485761,
        allocated: 10485760,
        isDir: true
      }
    ]);
  }
);

test(
  'PowerShell 编码识别：UTF-8/BOM 用 UTF-8，无 BOM 的 GBK 字节改用系统 ANSI 编码',
  {
    skip: !available
  },
  () => {
    const directory = fs.mkdtempSync(path.join(os.tmpdir(), '编码 测试 '));
    const header = 'File Name,Size,Allocated\r\n"C:\\Users\\';
    const tail = '\\Downloads\\",20971520,20971520\r\n';
    const files = {
      bom: Buffer.concat([
        Buffer.from([0xef, 0xbb, 0xbf]),
        Buffer.from(header + '中文' + tail)
      ]),
      utf8: Buffer.from(header + '中文' + tail),
      // 「中文」的 GBK 字节
      gbk: Buffer.concat([
        Buffer.from(header),
        Buffer.from([0xd6, 0xd0, 0xce, 0xc4]),
        Buffer.from(tail)
      ])
    };
    const checks = [];
    for (const [name, data] of Object.entries(files)) {
      const file = path.join(directory, name + '.csv');
      fs.writeFileSync(file, data);
      const expected = name === 'gbk' ? 'Default' : 'UTF8';
      checks.push(
        "if (-not [object]::ReferenceEquals((Get-CsvEncoding -CsvPath " +
          quote(file) +
          '), [Text.Encoding]::' +
          expected +
          ")) { throw '" +
          name +
          "' }"
      );
    }
    const command =
      '. ' +
      quote(path.join(__dirname, '../src/diskpilot-lite.ps1')) +
      ' -NoRun; ' +
      checks.join('; ');
    const run = spawnSync(pwsh, ['-NoProfile', '-Command', command], {
      encoding: 'utf8'
    });
    assert.equal(run.status, 0, run.stdout + run.stderr);
  }
);
