'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const { pathToFileURL } = require('node:url');
const browserPath = process.env.CHROME || '/usr/bin/google-chrome';
let chromium;
try {
  ({ chromium } = require('playwright-core'));
} catch {
  try {
    ({ chromium } = require('/workspace/tools/node_modules/playwright-core'));
  } catch {}
}
test(
  '浏览器实测：离线示例、勾选、导入、两种保存方式与重新打开',
  {
    skip: !chromium || !fs.existsSync(browserPath)
  },
  async () => {
    const browser = await chromium.launch({
      executablePath: browserPath,
      headless: true,
      args: ['--no-sandbox']
    });
    try {
      const context = await browser.newContext({
        acceptDownloads: true
      });
      const page = await context.newPage();
      const errors = [];
      const network = [];
      page.on('pageerror', (error) => errors.push(error.message));
      page.on('request', (request) => {
        if (/^https?:/.test(request.url())) {
          network.push(request.url());
        }
      });
      const directory = fs.mkdtempSync(path.join(os.tmpdir(), '报告浏览器 '));
      const html = fs
        .readFileSync(path.join(__dirname, '../src/report.html'), 'utf8')
        .replace('/*{{STYLE}}*/', () =>
          fs.readFileSync(path.join(__dirname, '../src/style.css'), 'utf8')
        );
      let built = html;
      for (const [key, name] of [
        ['CORE', 'core'],
        ['RULES', 'rules'],
        ['DEMO', 'demo-data'],
        ['APP', 'app']
      ]) {
        built = built.replace('/*{{' + key + '}}*/', () =>
          fs.readFileSync(
            path.join(__dirname, '../src/' + name + '.js'),
            'utf8'
          )
        );
      }
      const viewer = path.join(directory, '报告.html');
      fs.writeFileSync(viewer, built);
      await page.goto(pathToFileURL(viewer).href);
      assert.match(
        await page.locator('.source').innerText(),
        /示例数据（不是你的电脑）/
      );
      assert.ok((await page.locator('.card').count()) > 0);
      assert.equal(
        await page.locator('input[type=checkbox]:checked').count(),
        0
      );
      assert.equal(
        await page.locator('#selected').innerText(),
        '你还没有勾选任何建议'
      );
      assert.equal(
        await page
          .locator('#file')
          .evaluate((element) => element.classList.contains('visually-hidden')),
        true
      );
      for (const tierName of ['medium', 'heavy', 'light']) {
        await page.locator('#tab-' + tierName).click();
        assert.equal(
          await page.locator('input[type=checkbox]:checked').count(),
          0
        );
      }
      await page.locator('#file').focus();
      assert.equal(
        await page
          .locator('#file')
          .evaluate((element) => document.activeElement === element),
        true
      );
      const fileChooserPromise = page.waitForEvent('filechooser');
      await page.locator('label[for="file"]').click();
      const fileChooser = await fileChooserPromise;
      assert.equal(await fileChooser.element().getAttribute('id'), 'file');
      const before = await page.locator('#selected').innerText();
      await page.locator('.card input').first().check();
      const after = await page.locator('#selected').innerText();
      assert.notEqual(before, after);
      assert.match(after, /^你已勾选：约 [0-9.]+ GB$/);
      await page.locator('.card input').first().uncheck();
      assert.equal(await page.locator('#selected').innerText(), before);
      await page.locator('.card input').first().check();
      let downloadPromise = page.waitForEvent('download');
      await page.locator('#save').click();
      const download = await downloadPromise;
      const saved = path.join(directory, '已保存.html');
      await download.saveAs(saved);
      await page.goto(pathToFileURL(saved).href);
      assert.equal(await page.locator('#selected').innerText(), after);
      assert.match(
        await page.locator('.source').innerText(),
        /示例数据.*已保存的报告/
      );
      assert.equal(await page.locator('.card input').first().isChecked(), true);
      const csv =
        'Generated by WizTree\r\nFile Name,Size,Allocated\r\n"C:\\Users\\中文\\Downloads\\",1073741824,1073741824\r\n';
      await page.locator('#file').setInputFiles({
        name: '中文扫描.csv',
        mimeType: 'text/csv',
        buffer: Buffer.concat([
          Buffer.from([255, 254]),
          Buffer.from(csv, 'utf16le')
        ])
      });
      await page.waitForFunction(() =>
        document.querySelector('.source').textContent.includes('中文扫描.csv')
      );
      assert.match(await page.locator('h1').innerText(), /1.0 GB/);
      assert.match(
        await page.locator('#suggestions').innerText(),
        /这一档暂无可勾建议/
      );
      await page.locator('#tab-heavy').click();
      assert.match(await page.locator('.paths').innerText(), /中文\\Downloads/);
      assert.equal(
        await page.locator('input[type=checkbox]:checked').count(),
        0
      );
      assert.match(
        await page.locator('#status').innerText(),
        /已选择文件「中文扫描.csv」/
      );
      await page.locator('.card input').first().check();
      downloadPromise = page.waitForEvent('download');
      await page.locator('#save').click();
      const importedDownload = await downloadPromise;
      const now = new Date();
      const expectedName =
        'DiskPilot报告-' +
        now.getFullYear() +
        '-' +
        String(now.getMonth() + 1).padStart(2, '0') +
        '-' +
        String(now.getDate()).padStart(2, '0') +
        '.html';
      assert.equal(importedDownload.suggestedFilename(), expectedName);
      assert.equal(
        await page.locator('#save-status').innerText(),
        '已保存到浏览器的「下载」文件夹，文件名是 ' +
          expectedName +
          '，按 Ctrl+J 可以直接打开下载记录'
      );
      const importedSaved = path.join(directory, '导入已保存.html');
      await importedDownload.saveAs(importedSaved);
      await page.goto(pathToFileURL(importedSaved).href);
      assert.match(
        await page.locator('.source').innerText(),
        /你导入的 CSV（中文扫描.csv） · 已保存的报告/
      );
      assert.match(await page.locator('#selected').innerText(), /1.0 GB/);
      // GB18030 的中文路径与恶意标记均作为文本读取。
      const gb18030Csv = Buffer.concat([
        Buffer.from('File Name,Size,Allocated\r\n"C:\\Users\\'),
        Buffer.from([0xd6, 0xd0, 0xce, 0xc4]),
        Buffer.from('\\Downloads\\",50,50\r\n')
      ]);
      await page.locator('#file').setInputFiles({
        name: '旧编码.csv',
        mimeType: 'text/csv',
        buffer: gb18030Csv
      });
      await page.waitForFunction(() =>
        document.querySelector('.source').textContent.includes('旧编码.csv')
      );
      await page.locator('#tab-heavy').click();
      assert.match(await page.locator('.paths').innerText(), /中文/);
      await page.setViewportSize({
        width: 390,
        height: 844
      });
      assert.ok(
        await page.evaluate(
          () => document.documentElement.scrollWidth <= innerWidth
        )
      );
      await page.locator('#file').setInputFiles({
        name: '错误.csv',
        mimeType: 'text/csv',
        buffer: Buffer.from('不是表格')
      });
      await page.waitForFunction(() =>
        document.querySelector('#status').textContent.includes('读取失败')
      );
      assert.match(await page.locator('.source').innerText(), /旧编码.csv/);
      const malicious =
        'File Name,Size,Allocated\n"C:\\Users\\甲\\Downloads\\</script><script>window.被注入=true</script>\\",100,100\n"C:\\Users\\甲\\Downloads\\",100,100\n';
      await page.locator('#file').setInputFiles({
        name: '<危险>.csv',
        mimeType: 'text/csv',
        buffer: Buffer.from(malicious)
      });
      await page.waitForFunction(() =>
        document.querySelector('.source').textContent.includes('<危险>')
      );
      assert.equal(await page.evaluate(() => window.被注入), undefined);
      const real = built
        .replace(
          '<script type="text/plain" id="dp-embedded-csv"></script>',
          '<script type="text/plain" id="dp-embedded-csv">' + csv + '</script>'
        )
        .replace(
          '<script type="application/json" id="dp-embedded-meta">null</script>',
          '<script type="application/json" id="dp-embedded-meta">' +
            JSON.stringify({
              source: 'real',
              drive: 'C:',
              scannedAt: '2026-09-28T11:03:00',
              totalBytes: 200 * 1073741824,
              freeBytes: 3 * 1073741824
            }) +
            '</script>'
        );
      const realFile = path.join(directory, '真实报告.html');
      fs.writeFileSync(realFile, real);
      await page.goto(pathToFileURL(realFile).href);
      assert.match(
        await page.locator('.source').innerText(),
        /真实扫描 · C: · 2026-09-28 11:03/
      );
      downloadPromise = page.waitForEvent('download');
      await page.locator('#save').click();
      const realSaved = path.join(directory, '真实已保存.html');
      await (await downloadPromise).saveAs(realSaved);
      await page.goto(pathToFileURL(realSaved).href);
      assert.match(
        await page.locator('.source').innerText(),
        /真实扫描.*已保存的报告/
      );
      assert.match(await page.locator('h1').innerText(), /1.0 GB/);
      assert.equal(
        await page.locator('#selected').innerText(),
        '你还没有勾选任何建议'
      );

      // Save a result larger than the cap and inspect the actual embedded JSON.
      const manyFolders = ['File Name,Size,Allocated'];
      for (let index = 1; index <= 350; index++) {
        manyFolders.push(
          `"D:\\项目${index}\\node_modules\\",${index},${index}`
        );
      }
      await page.locator('#file').setInputFiles({
        name: '大量目录.csv',
        mimeType: 'text/csv',
        buffer: Buffer.from(manyFolders.join('\r\n'))
      });
      await page.waitForFunction(() =>
        document.querySelector('.source').textContent.includes('大量目录.csv')
      );
      await page.locator('#tab-medium').click();
      await page.locator('.card input').first().check();
      downloadPromise = page.waitForEvent('download');
      await page.locator('#save').click();
      const cappedReport = path.join(directory, '锚点上限.html');
      await (await downloadPromise).saveAs(cappedReport);
      await page.goto(pathToFileURL(cappedReport).href);
      const snapshot = await page
        .locator('#dp-embedded-result')
        .evaluate((element) => JSON.parse(element.textContent));
      const suggestion = snapshot.result.suggestions[0];
      assert.equal(suggestion.anchorCount, 350);
      assert.equal(suggestion.allAnchors.length, 300);
      assert.equal(suggestion.anchors.length, 50);
      assert.equal(suggestion.allAnchors[0].bytes, 350);
      assert.equal(suggestion.allAnchors[299].bytes, 51);
      assert.equal(snapshot.result.maxBytes, ((350 + 51) * 300) / 2);
      assert.deepEqual(snapshot.selected, ['dependencies']);
      await page.locator('#tab-medium').click();
      assert.equal(await page.locator('.card input').first().isChecked(), true);
      assert.deepEqual(errors, []);
      assert.deepEqual(network, []);
    } finally {
      await browser.close();
    }
  }
);
