(function (root, factory) {
  if (typeof module === 'object' && module.exports) {
    module.exports = factory();
  } else {
    root.DiskPilotDemo = factory();
  }
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  const rows = [
    ['C:', 180],
    ['C:\\Windows', 35],
    ['C:\\Windows\\Temp', 2],
    ['C:\\Windows\\SoftwareDistribution\\Download', 3],
    ['C:\\Program Files', 28],
    ['C:\\ProgramData', 8],
    ['C:\\$Recycle.Bin', 4],
    ['C:\\Users\\小明\\AppData', 40],
    ['C:\\Users\\小明\\AppData\\Local\\Temp', 3],
    [
      'C:\\Users\\小明\\AppData\\Local\\Microsoft\\Edge\\User Data\\Default\\Cache',
      2
    ],
    ['C:\\Users\\小明\\AppData\\Roaming\\DingTalk', 5],
    ['C:\\Users\\小明\\Documents', 30],
    ['C:\\Users\\小明\\Documents\\WeChat Files', 18],
    ['C:\\Users\\小明\\Documents\\Tencent Files', 6],
    ['C:\\Users\\小明\\Downloads', 15],
    ['C:\\Users\\小明\\Desktop', 8],
    ['C:\\Users\\小明\\Pictures', 5]
  ];
  return (
    'Generated by WizTree（虚构示例）\r\nFile Name,Size,Allocated,Modified,Attributes,Files,Folders\r\n' +
    rows
      .map(
        ([path, gigabytes]) =>
          '"' +
          path +
          '\\",' +
          gigabytes * 1073741824 +
          ',' +
          gigabytes * 1073741824 +
          ',,16,0,0'
      )
      .join('\r\n')
  );
});
